name: Git-Gov Verification

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main", "master" ]

jobs:
  verify-governance:
    name: 🛡️ Thermodynamic Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Important: Fetch full history for proper verification

    - name: Setup git-gov
      uses: git-gov/setup-git-gov@v1

    - name: Verify Head Commit
      id: verify
      shell: bash
      run: |
        echo "Verifying commit $(git rev-parse HEAD)..."
        
        OUTPUT=$(git-gov verify HEAD --format json)
        echo "Raw Output: $OUTPUT"
        STATUS=$(echo "$OUTPUT" | jq -r '.status')
        if [ "$STATUS" != "verified" ]; then
          echo "::error::Commit rejected! Low thermodynamic entropy detected."
          exit 1
        fi
        echo "✅ Commit verified with Score: $(echo "$OUTPUT" | jq -r '.score')"
